#!/usr/bin/env python

__author__ = 'thatcher'
import sys
from docker_container_runner import utils
from docker_container_runner.manager import Application, DockerDaemon, Hipache


# try:
#     settingsfile = sys.argv[3]
# except:
settingsfile = "settings.yml"

settings = utils.read_settings(settingsfile)


def initialize():
    """
    start it
    """

    directives = utils.read_appconfig(sys.argv[1])

    name, config = directives.items()[0]
    release_name = config['release_name']

    # Create the application
    application = Application(release_name, config, settings)

    # get (unitialized) containers
    containers = application.get_containers()

    for name, container in containers.items():
        print container.status

    return application


def create():
    application = initialize()
    application.create_containers()


def start():
    application = initialize()
    application.create_containers()
    application.start_containers()
    application.get_status()

def stop():
    application = initialize()
    application.stop_containers()


# setup the application from the config file
# applications = create_applications()

def print_usage():
    print \
    """
    usage:

    dcr.py [status|create|start|pull] [configfile.yml]
    """

try:
    stream = open(sys.argv[1])
except:
    print_usage()
    sys.exit(1)

directives = utils.read_appconfig(sys.argv[1])


cmd = sys.argv[2]

if cmd == "status":
    initialize()
elif cmd == "create":
    create()
elif cmd == "start":
    start()
elif cmd == "stop":
    stop()

elif cmd == "pull":
    application = initialize()
    application.login_registry()
    application.pull_image()

elif cmd == "register":
    try:
        domain = sys.argv[3]
    except BaseException as ex:
        sys.exit("please provide a domain name to register")

    application = initialize()
    application.register(domain)

elif cmd == "login":
    application = initialize()
    application.login_registry()

elif cmd == "remove":
    application = initialize()
    application.remove_containers()

else:
    print_usage()
    sys.exit(1)
